using System;
using zs.bcs.BobsCatSalesServices.Application.Enumerations;

namespace zs.bcs.BobsCatSalesServices.Application.Exceptions
{
    /// <summary>
    /// Exceptions generated by the application.
    /// </summary>
    public class ApplicationException : Exception
    {
        public ApplicationException(ApplicationConcern concern, ApplicationRules rule, string message) : base(message) { }

        public ApplicationException(ApplicationConcern concern, ApplicationRules rule, string message, Exception innerException) : base(message, innerException) { }
    }
}
