using System;
using zs.bcs.BobsCatSalesServices.Application.Enumerations;

namespace zs.bcs.BobsCatSalesServices.Application.Exceptions
{
    /// <summary>
    /// Exceptions generated by the application.
    /// </summary>
    public class ApplicationException : Exception
    {
        public ApplicationException(ApplicationConcern concern, ApplicationRules rule, string message) : base(message)
        {
            // TODO : Custom application exception building. exception can be against a calico-specific process or entity.
        }

        public ApplicationException(ApplicationConcern concern, ApplicationRules rule, string message, Exception innerException) : base(message, innerException)
        {
            // TODO : Custom application exception building. exception can be against a calico-specific process or entity.
        }
    }
}
